### ISSUE TITLE
using child_process.exec is a problem

### ISSUE THREAD

**Issue by avcreation** [containership/tesserarius#5]
Hi,

In your iptables.js module, you are using `child_process.exec` which can lead to severe security issue.

See by yourself:

```
> var Tesserarius = require("tesserarius");
> var tesserarius = new Tesserarius();
> tesserarius.create_chain('TEST; touch /tmp/THISISANEWFILE');
$ ls /tmp/
    ...
    THISISANEWFILE
    ...
```

You should consider using `child_process.spawn` instead, or be sure to escape any shell injection.

Hope you will find this helpfull,
Regards,

**Comment by normanjoyner** [comment]
thanks @avcreation this was fixed in a804d54fc6a36918403dc7efc8cfa04ff86d14ce
